### ISSUE TITLE
Cannot pay in the canteen

### ISSUE THREAD

**Issue by DaeLee96** [seit-gruppe14/world-of-oop#14]

**Comment by zlepper** [comment]
> pay
> Exception in thread "main" java.lang.NumberFormatException: null
>     at java.lang.Integer.parseInt(Integer.java:542)
>     at java.lang.Integer.parseInt(Integer.java:615)
>     at zuulFramework.worldofzuul.Canteen.buy(Canteen.java:29)
>     at zuulFramework.worldofzuul.Game.pay(Game.java:384)
>     at zuulFramework.worldofzuul.Game.processCommand(Game.java:223)

This issue is due to not having a second word in the command, telling the canteen how much they should buy for.
