### ISSUE TITLE
Integrere money / highscore 

### ISSUE THREAD

**Issue by SanderumChristian** [seit-gruppe14/world-of-oop#3]
Vi mangler at få et fungerende pengesystem sat ind i spillet og få en metode til beregne en highscore, når spillet er slut.

**Comment by zlepper** [comment]
Inden i slutter denne helt, skal i følge et kald til jeres slut metode here omkring: https://github.com/seit-gruppe14/world-of-oop/blob/master/src/zuulFramework/worldofzuul/Game.java#L476
