### ISSUE TITLE
En implementeringsbeskrivelse af centrale dele af spillet.

### ISSUE THREAD

**Issue by zlepper** [seit-gruppe14/world-of-oop#75]
En implementeringsbeskrivelse af centrale dele af spillet.

**Comment by Thorup** [comment]
Hey, har rykket rundt på vores opsætning af denne sektion, sådan at den er blevet mere generel, dette betyder at hver \subsection her definere hvilken pakke hvormed at ens primære forklaring tager sted, hvis man feks forklarer noget om **Controller** klassen, så hører den jo til pakken zuulFramework.worldofzuul.**gui**, hvilket betyder at man bør skrive i en \subsection{**GUI**} \subsubsection{**Controller**}. Er der nogle indvendinger til dette?
